USE Shmoop;

INSERT INTO Influencer (followerCount, bio, username)
VALUES (51, 'Persistent national time-frame', 'lparradiceq'),
       (26, 'Stand-alone leading edge migration', 'tbowlands1p'),
       (1, 'Public-key composite success', 'pduffil21'),
       (22, 'Mandatory mobile budgetary management', 'gbanister4'),
       (100, 'Visionary radical moratorium', 'ebreadon3n'),
       (41, 'Versatile transitional implementation', 'ejuett3s'),
       (58, 'Organized dynamic capacity', 'gbunt88'),
       (8, 'Re-contextualized local superstructure', 'kfenge11'),
       (28, 'Up-sized responsive initiative', 'lcaffery1j'),
       (90, 'Phased 24/7 definition', 'hhuggard21'),
       (64, 'Horizontal bi-directional complexity', 'mizak41'),
       (38, 'Extended bandwidth-monitored matrices', 'janedoe'),
       (5, 'Synchronized mission-critical installation', 'dkryszka2t'),
       (50, 'Fully-configurable clear-thinking framework', 'wsandilandsn'),
       (2, 'Integrated multi-state conglomeration', 'stedahl16'),
       (87, 'Vision-oriented user-facing parallelism', 'greckus1k'),
       (11, 'Monitored directional access', 'pschimon2o'),
       (3, 'Adaptive 24/7 project', 'tcornillir'),
       (25, 'User-friendly zero defect internet solution', 'rgianulli20'),
       (68, 'Optional encompassing strategy', 'bdooneyv'),
       (44, 'Distributed optimal forecast', 'thigounet7'),
       (84, 'Progressive multimedia forecast', 'keva80'),
       (62, 'Stand-alone multimedia collaboration', 'mscoggan6'),
       (67, 'Enterprise-wide upward-trending pricing structure', 'wriba17'),
       (95, 'Extended cohesive circuit', 'tviegas8a'),
       (54, 'Integrated asynchronous paradigm', 'astubbings2v'),
       (59, 'Synergized maximized firmware', 'aashdown3l'),
       (50, 'Managed methodical access', 'kvercruysse3g'),
       (52, 'Total bottom-line customer loyalty', 'oguitton11'),
       (7521, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'cstrelitzer87'),
       (1766, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'rgajewski3y'),
       (4357, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, c',
        'bwhymark6'),
       (6268, 'Proin at turpis a pede posuere nonummy.', 'tgoakesj'),
       (6421, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'kcharkham1v'),
       (7402, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'zantonin17'),
       (4529, 'Integer ac neque. Duis bibendum.', 'tari'),
       (5449, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'etompkin1k'),
       (11, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non veli', 'cbrauningeri'),
       (2283, 'Nulla mollis molestie lorem. Quisque ut erat.', 'jitzhayek45'),
       (1817, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, .', 'tshemmin1e'),
       (5276, 'Nulla nisl.', 'tstollberg1z'),
       (9230, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequa', 'cgoddman2n'),
       (8926, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vul', 'rissitt0'),
       (340, 'Donec ut dolor.', 'xmaldin8'),
       (6058, 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 'sdowdalls'),
       (2694, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'bwyant1f'),
       (3599, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus pu', 'lpatman19')
;

INSERT INTO InfluencerFollower (influencerusername, followerusername)
VALUES ('bwhymark6', 'npratton1e'),
       ('zantonin17', 'aurquhart2i'),
       ('ewiser', 'pculverhouse22'),
       ('mfontenot', 'pschimon2o'),
       ('mizak41', 'thigounet7'),
       ('tstollberg1z', 'wsandilandsn'),
       ('tgoakesj', 'rchichgar3w'),
       ('gbunt88', 'ygageng'),
       ('bwyant1f', 'dedwick13'),
       ('greckus1k', 'kvercruysse3g'),
       ('cstrelitzer87', 'mmcgirlx'),
       ('gbanister4', 'bbarzen86'),
       ('xmaldin8', 'jsemered2j'),
       ('mizak41', 'jsemered2j'),
       ('tshemmin1e', 'tari'),
       ('bdooneyv', 'bdooneyv'),
       ('tviegas8a', 'ygageng'),
       ('rissitt0', 'kgooderick1d'),
       ('astubbings2v', 'atrowela'),
       ('lpatman19', 'rtalby2c'),
       ('janedoe', 'chumbellh'),
       ('thigounet7', 'aurquhart2i'),
       ('aashdown3l', 'relvey2q'),
       ('tgoakesj', 'vgouley2z'),
       ('dkryszka2t', 'eheeneyk'),
       ('tshemmin1e', 'ogrindley14'),
       ('kfenge11', 'rpuckham3'),
       ('pduffil21', 'tfinan1h'),
       ('rissitt0', 'gshawl29'),
       ('cbrauningeri', 'thigounet7'),
       ('rissitt0', 'mivachyov1n'),
       ('thigounet7', 'jrobichon43'),
       ('rissitt0', 'rmeeland27'),
       ('mfontenot', 'lpeye2p'),
       ('tcornillir', 'vgouley2z'),
       ('bwhymark6', 'alangtry1u'),
       ('cgoddman2n', 'bwhymark6'),
       ('gbanister4', 'tshemmin1e'),
       ('stedahl16', 'ghabben1m'),
       ('aashdown3l', 'vmoxted37'),
       ('greckus1k', 'gwitheford34'),
       ('etompkin1k', 'rchichgar3w'),
       ('gbanister4', 'emckeaneyy'),
       ('greckus1k', 'ashrawley33'),
       ('zantonin17', 'mmaycock1b'),
       ('gbunt88', 'rsell89'),
       ('tgoakesj', 'bdooneyv'),
       ('ewiser', 'dedinburough3t'),
       ('sdowdalls', 'stedahl16'),
       ('cstrelitzer87', 'jmoring2'),
       ('lparradiceq', 'emckeaneyy'),
       ('janedoe', 'mwestgate2h'),
       ('keva80', 'thigounet7'),
       ('lparradiceq', 'ejuett3s'),
       ('mizak41', 'gphilip25'),
       ('lpatman19', 'kperet3q'),
       ('rgajewski3y', 'jkolyagin32'),
       ('lparradiceq', 'gbanister4'),
       ('aashdown3l', 'rsell89'),
       ('tbowlands1p', 'tjoncic0'),
       ('pschimon2o', 'lstallwood3c'),
       ('sdowdalls', 'tshemmin1e'),
       ('mizak41', 'rpuckham3'),
       ('keva80', 'lmidghall14'),
       ('tstollberg1z', 'khaggerty3m'),
       ('tstollberg1z', 'wriba17'),
       ('sdowdalls', 'thabble25'),
       ('mfontenot', 'cfeirn1b'),
       ('tari', 'rbridat13'),
       ('mizak41', 'kfenge11'),
       ('bwyant1f', 'jgrinston2x'),
       ('oguitton11', 'rgajewski3y'),
       ('ewiser', 'aashdown3l'),
       ('janedoe', 'abrithmanz'),
       ('janedoe', 'bhowarthc'),
       ('tgoakesj', 'ashrawley33'),
       ('bwyant1f', 'mmacfarlane1f'),
       ('mizak41', 'ashrawley33'),
       ('tgoakesj', 'credingtonf'),
       ('zantonin17', 'cpetry1l'),
       ('ewiser', 'oguitton11'),
       ('rgianulli20', 'kgiacobini2b'),
       ('wsandilandsn', 'elamburn28'),
       ('gbunt88', 'drosenbaum1i'),
       ('aashdown3l', 'ljarvie1x'),
       ('dkryszka2t', 'tviegas8a'),
       ('kvercruysse3g', 'pdilliway2'),
       ('greckus1k', 'amcgowan2y'),
       ('greckus1k', 'tfessions1z'),
       ('tstollberg1z', 'cfeirn1b'),
       ('mscoggan6', 'bcapner1d'),
       ('kcharkham1v', 'kblumson2u'),
       ('tbowlands1p', 'egillbanks5'),
       ('kfenge11', 'lstallwood3c'),
       ('ebreadon3n', 'mmercey7'),
       ('greckus1k', 'thabble25'),
       ('jitzhayek45', 'lpatman19'),
       ('wsandilandsn', 'hclemo1m'),
       ('lpatman19', 'tcornillir'),
       ('ebreadon3n', 'casif1l'),
       ('kfenge11', 'iseer1t'),
       ('stedahl16', 'hsalandino1q'),
       ('tari', 'mmaycock1b'),
       ('aashdown3l', 'qsinkin27'),
       ('cbrauningeri', 'vmoxted37'),
       ('rgianulli20', 'khaggerty3m'),
       ('rgianulli20', 'eheeneyk'),
       ('kcharkham1v', 'cdelascy1j'),
       ('aashdown3l', 'rsiemens3x'),
       ('jitzhayek45', 'jmcpakeo'),
       ('hhuggard21', 'gbunt88'),
       ('ejuett3s', 'keva80'),
       ('ebreadon3n', 'vfranzschoninger1s'),
       ('jitzhayek45', 'wriba17'),
       ('kcharkham1v', 'mbeckitt85'),
       ('janedoe', 'ljarvie1x'),
       ('cbrauningeri', 'rchichgar3w'),
       ('keva80', 'lstallwood3c'),
       ('etompkin1k', 'rtalby2c'),
       ('oguitton11', 'tviegas8a'),
       ('kvercruysse3g', 'cmcparlin30'),
       ('janedoe', 'nabello'),
       ('tari', 'rmarklund22'),
       ('etompkin1k', 'alamke42'),
       ('kcharkham1v', 'amcgowan2y'),
       ('zantonin17', 'lmillimoe2w'),
       ('mscoggan6', 'chumbellh'),
       ('etompkin1k', 'ppuckinghorne3b'),
       ('kfenge11', 'rmeeland27'),
       ('tviegas8a', 'mbeckitt85'),
       ('rgianulli20', 'rsiemens3x'),
       ('stedahl16', 'lprior1h'),
       ('aashdown3l', 'atrowela'),
       ('bwhymark6', 'kbrewoodm'),
       ('oguitton11', 'casif1l'),
       ('oguitton11', 'vgisburne38'),
       ('wriba17', 'tjosskoviz2k'),
       ('thigounet7', 'omelbury3e'),
       ('mscoggan6', 'mwestgate2h'),
       ('ejuett3s', 'hsalandino1q'),
       ('hhuggard21', 'lmidghall14'),
       ('rgajewski3y', 'keva80'),
       ('ebreadon3n', 'tshemmin1e'),
       ('tcornillir', 'kfautly8b'),
       ('bwhymark6', 'aurquhart2i'),
       ('kcharkham1v', 'cbousfield1i'),
       ('pduffil21', 'mwestgate2h'),
       ('bdooneyv', 'kwoodman1w'),
       ('tstollberg1z', 'lgreguoli82'),
       ('thigounet7', 'ieberz3o'),
       ('lparradiceq', 'tgoakesj'),
       ('ewiser', 'kcharkham1v'),
       ('janedoe', 'nburtwhistle5'),
       ('rgajewski3y', 'hsalandino1q'),
       ('lcaffery1j', 'mfontenot'),
       ('cstrelitzer87', 'tfessions1z'),
       ('tbowlands1p', 'vgouley2z'),
       ('oguitton11', 'ppuckinghorne3b'),
       ('hhuggard21', 'npratton1e'),
       ('dkryszka2t', 'gbanister4'),
       ('tviegas8a', 'omccheyne26'),
       ('rgajewski3y', 'jsemered2j'),
       ('mfontenot', 'elamburn28'),
       ('tari', 'wgurnelll'),
       ('tgoakesj', 'kgooderick1d'),
       ('aashdown3l', 'cbrauningeri'),
       ('tcornillir', 'astubbings2v'),
       ('ewiser', 'tshemmin1e'),
       ('lpatman19', 'lhurich2g'),
       ('kfenge11', 'emckeaneyy'),
       ('bdooneyv', 'mmcgirlx'),
       ('thigounet7', 'pgiovanardi3f'),
       ('bdooneyv', 'aurquhart2i'),
       ('tbowlands1p', 'cdelascy1j'),
       ('hhuggard21', 'ewiser'),
       ('hhuggard21', 'mmaycock1b'),
       ('mfontenot', 'mmacfarlane1f'),
       ('lpatman19', 'mmerigot12'),
       ('tari', 'kblumson2u'),
       ('pduffil21', 'rmeeland27'),
       ('mizak41', 'bbarzen86'),
       ('bwhymark6', 'ieberz3o'),
       ('bdooneyv', 'trandles35'),
       ('lcaffery1j', 'vfranzschoninger1s'),
       ('rissitt0', 'kcharkham1v'),
       ('thigounet7', 'lpatman19'),
       ('lparradiceq', 'rbernade3'),
       ('rgajewski3y', 'lcanaan9'),
       ('wriba17', 'tviegas8a'),
       ('etompkin1k', 'ogrindley14'),
       ('ewiser', 'dpickovert'),
       ('bdooneyv', 'kvercruysse3g'),
       ('ejuett3s', 'grisen18'),
       ('ebreadon3n', 'elamburn28'),
       ('tbowlands1p', 'pdilliway2'),
       ('tviegas8a', 'bwyant1f'),
       ('tstollberg1z', 'rmeeland27'),
       ('dkryszka2t', 'astubbings2v'),
       ('aashdown3l', 'ghabben1m'),
       ('tbowlands1p', 'relvey2q'),
       ('tshemmin1e', 'mmacfarlane1f'),
       ('zantonin17', 'alamke42'),
       ('tcornillir', 'bbarzen86'),
       ('dkryszka2t', 'pschimon2o'),
       ('oguitton11', 'ashrawley33'),
       ('tshemmin1e', 'rchichgar3w'),
       ('cstrelitzer87', 'nburtwhistle5'),
       ('hhuggard21', 'mbeckitt85'),
       ('lpatman19', 'ifruser3h'),
       ('wriba17', 'rsedgemondp'),
       ('jitzhayek45', 'tshemmin1e'),
       ('tcornillir', 'rsearl1g'),
       ('bdooneyv', 'rmeeland27'),
       ('kvercruysse3g', 'rsiemens3x'),
       ('tgoakesj', 'fnial84'),
       ('tari', 'hhindrich1y'),
       ('hhuggard21', 'lhurich2g'),
       ('kcharkham1v', 'ejuett3s'),
       ('cgoddman2n', 'gbunt88'),
       ('cgoddman2n', 'rmeeland27'),
       ('bwyant1f', 'bhandlin3p'),
       ('pschimon2o', 'iobell1c'),
       ('lparradiceq', 'jbarbrook3v'),
       ('sdowdalls', 'lstallwood3c'),
       ('tari', 'gmendez39'),
       ('lcaffery1j', 'hdillingston19'),
       ('etompkin1k', 'gshawl29'),
       ('gbunt88', 'jgrinston2x'),
       ('keva80', 'calsina1o'),
       ('gbanister4', 'ppuckinghorne3b'),
       ('pschimon2o', 'htrimble3d'),
       ('wriba17', 'emion4'),
       ('aashdown3l', 'gmendez39'),
       ('rgianulli20', 'omelbury3e'),
       ('tviegas8a', 'pdilliway2'),
       ('astubbings2v', 'sparkes1'),
       ('xmaldin8', 'swretham7z'),
       ('mizak41', 'aurquhart2i'),
       ('lparradiceq', 'mmercey7'),
       ('ebreadon3n', 'deastup28'),
       ('cstrelitzer87', 'rgajewski3y'),
       ('ewiser', 'vmoxted37'),
       ('tviegas8a', 'emion4'),
       ('bdooneyv', 'njandl2a'),
       ('etompkin1k', 'credingtonf'),
       ('tari', 'kbaudinot1g'),
       ('wsandilandsn', 'ssavory23'),
       ('zantonin17', 'mmcgirlx'),
       ('hhuggard21', 'jsemered2j'),
       ('kvercruysse3g', 'mfontenot'),
       ('greckus1k', 'ataverner16'),
       ('tgoakesj', 'iobell1c'),
       ('astubbings2v', 'rmacdearmid23'),
       ('cgoddman2n', 'ccliff2l'),
       ('gbunt88', 'kbaudinot1g'),
       ('xmaldin8', 'astubbings2v'),
       ('tcornillir', 'pgiovanardi3f'),
       ('dkryszka2t', 'pduffil21'),
       ('ebreadon3n', 'tjoncic0'),
       ('ebreadon3n', 'tjosskoviz2k'),
       ('janedoe', 'oguitton11'),
       ('lcaffery1j', 'amcgowan2y'),
       ('kvercruysse3g', 'alangtry1u'),
       ('lpatman19', 'emckeaneyy'),
       ('etompkin1k', 'dedwick13'),
       ('oguitton11', 'ghabben1m'),
       ('thigounet7', 'jitzhayek45'),
       ('janedoe', 'bboytond'),
       ('lpatman19', 'vgouley2z'),
       ('oguitton11', 'cbousfield1i'),
       ('aashdown3l', 'dpickovert'),
       ('bwhymark6', 'gshawl29'),
       ('pschimon2o', 'rchichgar3w'),
       ('lpatman19', 'aniceberg'),
       ('mscoggan6', 'kheifer2m'),
       ('sdowdalls', 'kblumson2u'),
       ('rgajewski3y', 'fhasluck3z'),
       ('janedoe', 'tviegas8a'),
       ('ewiser', 'tghirigori1c'),
       ('rgianulli20', 'cmogg1a'),
       ('wriba17', 'njandl2a'),
       ('xmaldin8', 'cdelascy1j'),
       ('janedoe', 'ataverner16'),
       ('kcharkham1v', 'hhuggard21'),
       ('ewiser', 'etompkin1k'),
       ('jitzhayek45', 'aashdown3l'),
       ('astubbings2v', 'kmaclardie2d'),
       ('xmaldin8', 'jkeyser3u'),
       ('thigounet7', 'kbrewoodm'),
       ('tbowlands1p', 'tjosskoviz2k'),
       ('lparradiceq', 'kbrewoodm'),
       ('ewiser', 'ataverner16'),
       ('astubbings2v', 'nabello'),
       ('jitzhayek45', 'rstrathe2e'),
       ('rgajewski3y', 'tgauthorpp36');


INSERT INTO Brand (name)
VALUES ('Eimbee'),
       ('Flipbug'),
       ('Realmix'),
       ('Blogtag'),
       ('Eadel'),
       ('Pixonyx'),
       ('Skimia'),
       ('Rhynoodle'),
       ('Wikizz'),
       ('Zoombeat'),
       ('Skipstorm'),
       ('Bubblebox'),
       ('Yotz'),
       ('Zazio'),
       ('Tavu'),
       ('Leexo'),
       ('Brightdog'),
       ('Mita'),
       ('Divape'),
       ('Livetube'),
       ('Dabfeed'),
       ('Roomm'),
       ('Wordpedia'),
       ('Livefish'),
       ('Meetz'),
       ('Trilia'),
       ('Mycat'),
       ('Lajo'),
       ('Trudeo'),
       ('Geba');

INSERT INTO Brand (name)
VALUES ('vestibulum'),
       ('donec'),
       ('habitasse'),
       ('dictumst'),
       ('mauris'),
       ('phasellus'),
       ('in'),
       ('nin'),
       ('consequat'),
       ('urna');

INSERT INTO Video (comments, likes, shares, duration, caption, brandname)
VALUES (9087, 4785, 9236, 24.56, 'Cras in purus eu magna vulputate luctus.', 'urna'),
       (8166, 6240, 879, 16.41, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Trilia'),
       (541, 2407, 5896, 38.1,
        'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
        'donec'),
       (6230, 519, 4073, 34.41,
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Skimia'),
       (7375, 8732, 219, 24.83, 'Cras pellentesque volutpat dui Vestibulum ante ipsum pram.', 'Nike'),
       (1056, 665, 1418, 22.44, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
        'Zoombeat'),
       (6782, 3844, 5776, 36.5, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 'mauris'),
       (4120, 9806, 2092, 46.28, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt l', 'Brightdog'),
       (4190, 5123, 4774, 14.44,
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
        'in'),
       (7379, 497, 2848, 7.72, 'Phasellus in felis.', 'Brightdog'),
       (839, 1818, 7004, 29.45, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'urna'),
       (784, 3546, 1710, 56.58, 'Nulla justo.', 'Meetz'),
       (8390, 8304, 2994, 26.75, 'Maecenas tristique, est et teere cubilia Curae, Mauris viverra diam ', 'mauris'),
       (3548, 971, 5563, 2.8, 'Proin risus. Praesent lectus.', 'Skimia'),
       (3541, 7157, 6399, 31.14, 'Integer tincidunt ante vel ipsum.', 'Realmix'),
       (8703, 9457, 4330, 22.2, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Trudeo'),
       (2605, 7757, 8034, 47.8, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Eimbee'),
       (6915, 8658, 509, 52.39, ', sit amet eleifend pede libero quis orci.', 'Livetube'),
       (1124, 9130, 2291, 43.26, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'habitasse'),
       (6243, 129, 9828, 21.22, 'pien dignissim vestibulum.', 'urna'),
       (9971, 5222, 1726, 27.92, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'Mycat'),
       (8279, 6213, 8894, 29.46, 'elementum eu, interdum eu, tincidunt in, leo.', 'Trudeo'),
       (84, 1964, 1669, 51.38, ' eleifend pede libero quis orci.', 'Flipbug'),
       (1965, 7126, 6561, 6.02, 'In quis justo. Maecenas rhoncus aliquam lacus.', 'consequat'),
       (9332, 5411, 300, 24.44, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
        'Wikizz'),
       (8496, 8411, 7902, 16.77, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'Realmix'),
       (2576, 9571, 8889, 54.91, 'Donec odio justo.', 'Leexo'),
       (3110, 7909, 9189, 19.85, 'Vivamus vel nulla eget eros elementum pellentesque.', 'Rhynoodle'),
       (3534, 4375, 420, 44.69, 'Nunc rhoncus dui vel sem.', 'Tavu'),
       (6931, 9535, 5456, 52.07, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 'Tavu'),
       (344, 5070, 5021, 5.3,
        'Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Zoombeat'),
       (8476, 9187, 8458, 22.95,
        'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'Tavu'),
       (6832, 4413, 4826, 11.41,
        'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Leexo'),
       (7690, 8590, 4409, 30.59,
        'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'Trudeo'),
       (7525, 6324, 8186, 31.58,
        'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Bubblebox'),
       (9762, 9770, 7835, 7.34, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Wikizz'),
       (7580, 5600, 9648, 38.75, 'Quisque ut erat. Curabitur gravida nisi at nibh.', 'in'),
       (1580, 8882, 1345, 47.78, 'Nunc nisl. Duis bibendum, felis sed interdum .', 'Eimbee'),
       (1192, 6457, 8977, 26.19, 'Etiam faucibus cursus urna. Ut tellus.', 'phasellus'),
       (7323, 7882, 3812, 8.04,
        'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
        'Livetube'),
       (608, 1177, 2055, 44.85, 'Sed ante.', 'Eadel'),
       (2408, 2042, 182, 29.11, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'Roomm'),
       (4789, 1206, 6325, 34.9, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'Bubblebox'),
       (2367, 3075, 2618, 27.33, 'Curabitur in libero ut massa volutpat convallis.', 'Nike'),
       (320, 4674, 2914, 21.61, 'Etiam faucibus cursus urna. Ut tellus.', 'Lajo'),
       (4337, 9533, 4031, 42.55, 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet',
        'Realmix'),
       (1436, 8115, 4173, 10.82,
        'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',
        'mauris'),
       (1880, 4742, 2934, 59.4, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'dictumst'),
       (7495, 4346, 8159, 52.98,
        'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.',
        'vestibulum'),
       (4685, 6962, 5983, 56.04, 'Donec ut mauris eget massa tempor convallis.', 'Livefish'),
       (2873, 3626, 1299, 27.51,
        'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
        'Realmix'),
       (7731, 9972, 6923, 53.53,
        'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer alel accumsan tellus nisi eu orci. M.',
        'Eadel'),
       (6287, 3988, 9741, 45.68,
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultricellicitudin mi, sit amet lobortis sapien sapien non mi.',
        'Leexo'),
       (3169, 6556, 3459, 44.08,
        'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Divape'),
       (6281, 4451, 4538, 7.27,
        'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',
        'Lululemon'),
       (9716, 2202, 5865, 48.07,
        'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
        'vestibulum'),
       (9907, 8307, 8238, 6.61, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
        'habitasse'),
       (2485, 7602, 4059, 45.23, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Trudeo'),
       (3756, 6894, 7192, 58.14, 'Donec diam neque, vestibulum eget, mi, sit amet lobortis sapien sapien non mi.',
        'Dabfeed'),
       (5345, 4515, 1078, 8.25, 'Ut at dolor quis odio consequat varius. Integer ac leo.', 'Eimbee');

SELECT id
FROM Video;

INSERT INTO Posts(influencerUsername, videoId)
VALUES ('kcharkham1v', 117),
('ejuett3s', 29),
('zantonin17', 77),
('lcaffery1j', 72),
('aashdown3l', 6),
('cgoddman2n', 77),
('wsandilandsn', 108),
('tbowlands1p', 112),
('kvercruysse3g', 51),
('mfontenot', 88),
('gbunt88', 85),
('ejuett3s', 108),
('hhuggard21', 22),
('aashdown3l', 124),
('tshemmin1e', 98),
('tviegas8a', 23),
('zantonin17', 49),
('stedahl16', 110),
('sdowdalls', 102),
('zantonin17', 118),
('tshemmin1e', 97),
('ebreadon3n', 38),
('mscoggan6', 13),
('pschimon2o', 66),
('wsandilandsn', 18),
('kcharkham1v', 40),
('wriba17', 67),
('etompkin1k', 102),
('ebreadon3n', 62),
('lpatman19', 26),
('bdooneyv', 6),
('xmaldin8', 77),
('dkryszka2t', 68),
('rissitt0', 56),
('jitzhayek45', 5),
('cstrelitzer87', 101),
('janedoe', 72),
('ewiser', 22),
('etompkin1k', 105),
('tstollberg1z', 26),
('pschimon2o', 71),
('rissitt0', 54),
('ewiser', 111),
('dkryszka2t', 60),
('janedoe', 125),
('cstrelitzer87', 28),
('tstollberg1z', 28),
('dkryszka2t', 37),
('keva80', 13),
('astubbings2v', 83),
('tshemmin1e', 90),
('ebreadon3n', 40),
('pduffil21', 120),
('kfenge11', 84),
('etompkin1k', 27),
('wriba17', 48),
('gbunt88', 51),
('tbowlands1p', 61),
('ewiser', 62),
('tshemmin1e', 85),
('aashdown3l', 12),
('astubbings2v', 100),
('hhuggard21', 93),
('astubbings2v', 55),
('hhuggard21', 15),
('jitzhayek45', 93),
('janedoe', 34),
('ejuett3s', 35),
('cbrauningeri', 97),
('lpatman19', 105),
('thigounet7', 112),
('cstrelitzer87', 46),
('tari', 26),
('ewiser', 84),
('mscoggan6', 82),
('xmaldin8', 110),
('lparradiceq', 117),
('thigounet7', 74),
('wriba17', 40),
('zantonin17', 124),
('lparradiceq', 19),
('astubbings2v', 2),
('sdowdalls', 6),
('oguitton11', 8),
('rgianulli20', 26),
('lparradiceq', 108),
('thigounet7', 122),
('lpatman19', 8),
('aashdown3l', 96),
('pduffil21', 79),
('dkryszka2t', 33),
('wriba17', 121),
('dkryszka2t', 113),
('etompkin1k', 2),
('zantonin17', 44),
('pschimon2o', 20),
('oguitton11', 108),
('keva80', 29),
('etompkin1k', 6),
('tcornillir', 30),
('mfontenot', 99),
('jitzhayek45', 42),
('bdooneyv', 80),
('janedoe', 14),
('bdooneyv', 42),
('kcharkham1v', 99),
('ejuett3s', 113),
('rissitt0', 73),
('mizak41', 36),
('etompkin1k', 51),
('tstollberg1z', 40),
('cbrauningeri', 85),
('mfontenot', 13),
('etompkin1k', 84),
('oguitton11', 46),
('kcharkham1v', 85),
('mscoggan6', 92),
('ejuett3s', 114),
('zantonin17', 50),
('aashdown3l', 39),
('lpatman19', 37),
('tviegas8a', 69),
('wsandilandsn', 66),
('ejuett3s', 58),
('wriba17', 88),
('bdooneyv', 93),
('ebreadon3n', 9),
('cgoddman2n', 8),
('jitzhayek45', 54),
('thigounet7', 76),
('tari', 45),
('janedoe', 21),
('cbrauningeri', 124),
('tstollberg1z', 14),
('tstollberg1z', 83),
('bdooneyv', 124),
('bdooneyv', 81),
('xmaldin8', 76),
('kfenge11', 10),
('ebreadon3n', 84),
('zantonin17', 125),
('rgajewski3y', 8),
('keva80', 22),
('tviegas8a', 32),
('cgoddman2n', 34),
('bdooneyv', 105),
('cstrelitzer87', 47),
('janedoe', 82),
('kcharkham1v', 47),
('gbanister4', 55),
('bwyant1f', 21),
('ewiser', 101),
('dkryszka2t', 119),
('thigounet7', 26),
('bwhymark6', 33),
('cgoddman2n', 85),
('cgoddman2n', 109),
('zantonin17', 69),
('gbanister4', 81),
('ewiser', 96),
('kcharkham1v', 100),
('tari', 114),
('stedahl16', 31),
('lcaffery1j', 1),
('mfontenot', 78),
('gbunt88', 17),
('oguitton11', 16),
('kcharkham1v', 54),
('stedahl16', 27),
('lpatman19', 3),
('rissitt0', 33),
('thigounet7', 85),
('wsandilandsn', 54),
('sdowdalls', 117),
('tcornillir', 22),
('ebreadon3n', 110),
('kvercruysse3g', 53),
('ejuett3s', 115),
('kvercruysse3g', 5),
('ejuett3s', 2),
('wriba17', 106),
('tbowlands1p', 110),
('lcaffery1j', 37),
('gbanister4', 64),
('mizak41', 119),
('rissitt0', 56),
('oguitton11', 85),
('tgoakesj', 125),
('pschimon2o', 47),
('janedoe', 50),
('janedoe', 109),
('tbowlands1p', 93),
('astubbings2v', 97),
('tgoakesj', 69),
('oguitton11', 82),
('dkryszka2t', 78),
('dkryszka2t', 99),
('wriba17', 64),
('wsandilandsn', 11),
('pduffil21', 95),
('lpatman19', 22),
('greckus1k', 52),
('wsandilandsn', 29),
('hhuggard21', 32),
('stedahl16', 26),
('kfenge11', 13),
('tviegas8a', 26),
('xmaldin8', 73),
('cbrauningeri', 106),
('rissitt0', 10),
('kvercruysse3g', 1),
('tviegas8a', 97),
('kcharkham1v', 38),
('janedoe', 46),
('pschimon2o', 104),
('rgajewski3y', 110),
('gbunt88', 107),
('ewiser', 59),
('oguitton11', 48),
('oguitton11', 122),
('mfontenot', 93),
('pschimon2o', 62),
('keva80', 56),
('stedahl16', 109),
('bwhymark6', 3),
('etompkin1k', 66),
('mizak41', 80),
('tbowlands1p', 1),
('tcornillir', 47),
('jitzhayek45', 33),
('lparradiceq', 50),
('jitzhayek45', 46),
('pduffil21', 121),
('mfontenot', 80),
('tviegas8a', 27),
('sdowdalls', 109),
('tgoakesj', 39),
('etompkin1k', 14),
('cbrauningeri', 79),
('rgajewski3y', 29),
('lpatman19', 112),
('keva80', 73),
('tshemmin1e', 44),
('kcharkham1v', 2),
('lcaffery1j', 8),
('greckus1k', 102),
('bwyant1f', 17),
('gbanister4', 32),
('jitzhayek45', 106),
('sdowdalls', 20),
('mizak41', 66),
('jitzhayek45', 14),
('gbanister4', 39),
('gbanister4', 108),
('cgoddman2n', 36),
('tshemmin1e', 52),
('rgajewski3y', 79),
('tviegas8a', 24),
('kfenge11', 3),
('hhuggard21', 26),
('tstollberg1z', 82),
('gbunt88', 40),
('pschimon2o', 12),
('lparradiceq', 43),
('lparradiceq', 84),
('mizak41', 33),
('bwhymark6', 86),
('tari', 25),
('jitzhayek45', 25),
('oguitton11', 67),
('rissitt0', 2),
('tbowlands1p', 49),
('tbowlands1p', 50),
('rissitt0', 87),
('tbowlands1p', 77),
('xmaldin8', 27),
('bwhymark6', 49),
('bwyant1f', 76),
('kcharkham1v', 95),
('lparradiceq', 59),
('pschimon2o', 11),
('wriba17', 44),
('tari', 108),
('rissitt0', 115),
('bdooneyv', 77),
('dkryszka2t', 51),
('stedahl16', 103),
('lcaffery1j', 119),
('stedahl16', 66),
('gbunt88', 50),
('greckus1k', 54),
('greckus1k', 29),
('sdowdalls', 22),
('bwhymark6', 16),
('mfontenot', 55),
('hhuggard21', 103),
('tstollberg1z', 86),
('stedahl16', 85),
('mizak41', 102),
('tviegas8a', 29);